### PR TITLE
Major Refactor

### PR DESCRIPTION
**Pull request by Expl0dingBanana**
* Update the integration to be configured via UI
 * Refactor all entities to be correctly represented, rather than a light
 * Refactor all code to by async compatible
 * Entity creation now uses a coordinator to reduce the amount of calls to the API after splitting out the entities
 * Use a third-party library, hubspace-async, for all requests. The session for home assistant is sent to the package
 * Standardize the discovery pipeline to use automatic discovery for all devices
 * Removed the ability to specify friendlyNames and roomNames
 * Update README to specify how to generate device information used for testing

Sem-Ver: api-break

I am currently using this to control my Zandra Fan (light + fan). The only issue I have seen so far is the brightness is correctly set, but when you close and go back in, it will always show 1%. However this does not affect functionality.

Configuration Screen:
image

Device registration (i only have one device) after clicking submit
image

Integration Screen
image

Light entity (showing that sweet 1% at start)
image

Fan entity
image

Device page
image

Generating test data (example output can be found @ tests/device_dumps/fan_zandra.json [i did rename this or it would have been office_fan.json])
```
python anonomyize_data.py --username "<nope>" --password "<nope>" get-devs
python anonomyize_data.py --username "<nope>" --password "<nope>" friendly-name --fn "Office Fan"
python anonomyize_data.py --username "<nope>" --password "<nope>" child-id --child_id "<a unique id>"
```

### CODE REVIEW

**Comment by jdeath** [comment]
This is awesome. I will test in a few hours and merge. If it works, it might be good enough to make a core integration as you made a real library.

**Comment by Expl0dingBanana** [comment]
I did not do anything with the services but focused on getting the entities added in. I found an issue with the anonymizer so I will need to fix that. I also need to fix / write some UTs to ensure that it continues to work 😅

**Comment by jdeath** [comment]
This is not working for me. I downloaded your latest ` Expl0dingBanana:complete-rework` branch. It auto finds my devices in the config_flow, and shows 3 devices, but no entities/controls attached to them. Only light, plug, and lock.

**Comment by Expl0dingBanana** [comment]
> This is not working for me. I downloaded your latest ` Expl0dingBanana:complete-rework` branch. It auto finds my devices in the config_flow, and shows 3 devices, but no entities/controls attached to them. Only light, plug, and lock.

I noticed sometimes it takes a cycle or two for them to appear. Did it sit for 30s or so with no entities still showing?

**Comment by jdeath** [comment]
> I noticed sometimes it takes a cycle or two for them to appear. Did it sit for 30s or so with no entities still showing?

Waited 5 minutes or so. And did a reboot. Then did an disable/enable/reboot cycle too. Removed the old hubspace config, reboot and wait a few minutes. No entities...

**Comment by Expl0dingBanana** [comment]
Trying to pick my brain what it would be if there are no logs. The light entity forces everything to have a device 😅 but I would still expect to see entities.

Can you force the logger into debug during initial setup? Adding this to configuration.yaml will force the namespace into debug

```yaml

logger:
  default: error
  logs:
    custom_components.hubspace: debug
```

**Comment by jdeath** [comment]
A bunch of json showing my entities then got:
```
2024-07-24 19:21:35.000 DEBUG (MainThread) [custom_components.hubspace.coordinator] Finished fetching hubspace data in 1.004 seconds (success: True)
2024-07-24 19:21:35.004 DEBUG (MainThread) [custom_components.hubspace.fan] Unable to process the entity XXXroom of class switch
2024-07-24 19:21:35.005 DEBUG (MainThread) [custom_components.hubspace.fan] Unable to process the entity Front Door of class door-lock
2024-07-24 19:21:35.005 DEBUG (MainThread) [custom_components.hubspace.fan] Unable to process the entity Plug of class power-outlet
2024-07-24 19:21:35.006 DEBUG (MainThread) [custom_components.hubspace.light] Unable to process the entity XXXroom of class switch
2024-07-24 19:21:35.006 DEBUG (MainThread) [custom_components.hubspace.light] Unable to process the entity Front Door of class door-lock
2024-07-24 19:21:35.006 DEBUG (MainThread) [custom_components.hubspace.light] Unable to process the entity Plug of class power-outlet
2024-07-24 19:21:35.006 DEBUG (MainThread) [custom_components.hubspace.switch] Unable to process the entity XXXroom of class switch
2024-07-24 19:21:35.007 DEBUG (MainThread) [custom_components.hubspace.switch] Unable to process the entity Front Door of class door-lock
2024-07-24 19:21:35.008 DEBUG (MainThread) [custom_components.hubspace.valve] Unable to process the entity XXXroom of class switch
2024-07-24 19:21:35.008 DEBUG (MainThread) [custom_components.hubspace.valve] Unable to process the entity Front Door of class door-lock
2024-07-24 19:21:35.008 DEBUG (MainThread) [custom_components.hubspace.valve] Unable to process the entity Plug of class power-outlet
```

Devices have correct model number, just no entities. Not sure why saying its a valve.... Only have a lock, light and plug...

**Comment by Expl0dingBanana** [comment]
> Devices have correct model number, just no entities. Not sure why saying its a valve.... Only have a lock, light and plug...

A water-timer is implemented as a valve. It sends all data to every entity type. Maybe I should refactor that a bit so it sends indexed data based on deviceClass rather than a list of everything. That would reduce the useless messages.

Is your light a switch? I noticed within `switch.py` I only process `power-outlet` and `landscape-transformer`, not `switch`. 

However the log message isnt present for the outlet, but I also dont see a success message so it tried to process the outlet but did so unsuccessfully.  When processing a `power-outlet`, I expected `toggle` function to identify the outlets which was based on `sample_data/outlets.json`. Can you attach the json dump (should already be anonymized), or run the anonymizer script for each of the three devices? You can add it to my branch under `tests/device_dumps` or attach it to this PR.

I can take a look to see what I expected and whats actually returned to ensure it works.

**Comment by jdeath** [comment]
Here you go.
[XXXroom.json](https://github.com/user-attachments/files/16368621/XXXroom.json)
[Plug.json](https://github.com/user-attachments/files/16368622/Plug.json)
[Front Door.json](https://github.com/user-attachments/files/16368623/Front.Door.json)

**Comment by Expl0dingBanana** [comment]
Ah, I see why that switch is a light. Its a dimmer, which a switch entity does not support. Let me write some tests tonight and I will try to get a fix out today / tomorrow.

**Comment by jdeath** [comment]
> Was this switch previously on/off + brightness?

Yes, on/off brightness. The very first device supported, since only one I owned. But why don't all the others work? No worries, will not get to test till tomorrow anyways

**Comment by Expl0dingBanana** [comment]
I never implemented the device lock. I think when I was splitting things out I missed that. For the power-outlet, I only had `outlets.json` which referenced functionClass=`toggle` within the functions, so I thought that was standard. Your dump does not have these states, which is why nothing was added.

**Comment by jdeath** [comment]
> I need to review the special processing you had in `HubspaceLight` as it did some extra model processing in there
Got it. I probably never uploaded dumps for my own devices. The TestHubspace was written by another user to help people get support. I never needed it...

**Comment by Expl0dingBanana** [comment]
I added tests for the dimmer (light), door-lock, and outlet. However I do not have tests for the setup so I have not validate that works properly yet. If you want to test it tomorrow, use the tag `test` and it should grab that one.

**Comment by Expl0dingBanana** [comment]
@jdeath I think this should work for you now. I also added sensors (battery and wifi-rssi [for testing]) so the lock should now show that information (assuming it discovers properly).

**Comment by jdeath** [comment]
Used your commit from a few minutes ago. 
- Light works fine, dimmer starts at 1%, but then does work correctly
- Lock shows entity, unlock/lock does not work, does not report correct state, battery shows.
- Plug does not show an entity

If you look at logic and commands for lock/plug in my original code hopefully you can see what command needs to be sent.  For lock, the command should be:
setState(self._childId, "lock-control", "locking") to lock
setState(self._childId, "lock-control", "unlocking") to unlock

The "plug" is not an outlet, it does not have an index.
The commands are simply "on" and "off". The plug does not need anything extra, just these commands. Hope that helps.

**Comment by Expl0dingBanana** [comment]
Tonight I tracked down the dimmer issue. It was related to the default state of `ColorMode.UNKNOWN` which apparently breaks brightness.

Ill be honest, I did not review the original code yet for locks / outlets. I based it off the states which appeared to use right / left for lock, not `lock-control` as I missed that state. Let me take another whack at it tomorrow / this weekend when I have time to fully review all of the commands previously set.

**Comment by jdeath** [comment]
Sure. Appreciate you trying to improve this. The API is a not consistent for some devices. Right/left is the mode to which way to turn the lock, not the lock/unlock command. Took a while to figure everything out, and I never had the skills to learn the commands from the API.

**Comment by Expl0dingBanana** [comment]
@jdeath Locks should be fixed with 2708901. I have advanced the tag if you wanted to test it out.

**Comment by jdeath** [comment]
Lock still does not work for me with your code. I got it to actually lock with some changes, but it does not seem to be polling the state of the lock. It always thinks it is unlocked/open. Can you ensure it is polling the state?

To make it actually lock:

1) I removed the functionInstance line and the lock will now lock. The lock commands do not use functionInstance.

However, the UI is stuck on showing unlocking/locking. Even waiting a few minutes, the GUI does not update.

The UI should probably not show that, because it is an intermediate state. You have properties like is_locking / is_unlocking which should not be needed.

I tried adding this function to explicitly report if the lock is open, but it does not seemed to be called.
```
@property
    def is_open(self) -> bool:
        return not self._current_position == "locked"   
```

**Comment by bluedragon456** [comment]
@Expl0dingBanana way to go on getting into the UI and rebuilding. I tried your code to see how well it is along. Worked great at seeing everything. I know you're still working at it to get all the devices to work correctly. I have a diskrol fan and a water timer with the plug hub.  All was seen but the fan while it worked, I noticed while watching the hubspace app and testing the different setting the fan in the app would go offline, but it would still work. I'm not sure if it means anything but I thought I would report just in case it leads to something. My plug hub that came with the water timer is seen but has no control which not surprising as it never been able to get in a work without adding manually, and the water timer itself I didn't get a chance to fully look at, ran out of time but it loaded and had the entity's I just didn't confirm that they worked as they should.

**Comment by Expl0dingBanana** [comment]
> Lock still does not work for me with your code. I got it to actually lock with some changes, but it does not seem to be polling the state of the lock. It always thinks it is unlocked/open. Can you ensure it is polling the state?

The update should be coming from the coordinator through the function `_handle_coordinator_update`.  When it receives this update, it then searched for the state, `lock-control`, and sets the current position to the state. Was there any warnings in the logs about the lock? Maybe I misconfigured it so it refused to update. The next commit will have additional debug information at update time. These debug messages should appear every 30s if any updates are coming through for the lock.

> I removed the functionInstance line and the lock will now lock. The lock commands do not use functionInstance.

When I was setting the instance during lock / unlock, I copy / pasted from something and had the instance set to something, rather than empty. I bet thats why the control did not work.

> The UI should probably not show that, because it is an intermediate state. You have properties like is_locking / is_unlocking which should not be needed.

I tried to report all the data that is available, and these states are present for LockEntity. I think after we figure out why polling isnt updating the state it will be fine.

I am still confused on what `is_open` is used for. Theres locked, locking, unlocking, jammed, and open. Is open supposed to be unlocked? The core implementation is as follows:

```python
    @final
    @property
    def state(self) -> str | None:
        """Return the state."""
        if self.is_jammed:
            return STATE_JAMMED
        if self.is_opening:
            return STATE_OPENING
        if self.is_locking:
            return STATE_LOCKING
        if self.is_open:
            return STATE_OPEN
        if self.is_unlocking:
            return STATE_UNLOCKING
        if (locked := self.is_locked) is None:
            return None
        return STATE_LOCKED if locked else STATE_UNLOCKED
```

Anyways can you try with cb99060 and see if any logs come in for the lock?

**Comment by Expl0dingBanana** [comment]
@bluedragon456 
> All was seen but the fan while it worked, I noticed while watching the hubspace app and testing the different setting the fan in the app would go offline, but it would still work

When you make changes through the integration the hubspace app shows the device as offline? I think they have a rate limit setup and if you make too many changes, they temporarily block you. I spammed changing in HA for a minute or so and the device then went offline in HS and I couldn't control it in HA anymore. After a minute or two, the HS app showed it working and HA controls worked again.

Would it be possible to grab a data dump of the water timer? The integration was made off assumptions and having a dump of the device would be beneficial to it working.

**Comment by Expl0dingBanana** [comment]
Made some more changes to the code:

 * Added the ability to remove devices. A device can only be removed if its not being reported by the API
 * Added the manufacturer to the device
image

 * Force the hubspace_async logger level to match the component log level. This enables all hubspace-async logs to flow into the HA logs and you can clearly see what requests are being made for devices.
 * Move the logic for determining device class from hubspace-async into discovery. This will allow for updates in a single repo rather than two for this
 * Update switch and valves to follow the same discovery logic for "toggleable" (more than 1 per device) vs "non-togglable" (1 per device) devices.
 
 While I can't test the functionality, I jammed in the device dumps to the coordinator and saw that entities discovered correctly (for the dumps I have).

**Comment by bluedragon456** [comment]
Happy to do the data dump but I do not know how to do that. So if you can send me how I will get it posted. 

Reload the new change you made and the plug is working as it should now.

**Comment by Expl0dingBanana** [comment]
@bluedragon456 This guide in the README should work.

https://github.com/Expl0dingBanana/Hubspace-Homeassistant/blob/complete-rework/README.md#support-for-a-new-model

Preferably it would be the shell method, but going through the UI is fine too. Let me know if anything is confusing and I would be happy to clarify and update the readme!

**Comment by bluedragon456** [comment]
[gardendrip.json](https://github.com/user-attachments/files/16396076/gardendrip.json)
here is the data dump i was able to pull.

**Comment by jdeath** [comment]
- Plug now works.
- Light now works, dimmer set correctly on init.
- Lock will lock, but it still does not seem to be polling for the update. It defaults to unlocked and stays there. when I hit lock, the state stays at "locking" forever. So it never knows the correct state of the lock, so it cannot be controlled.

I have debug set, but I only get the json dump below. There is no logging for sending any commands, even though I see the `_LOGGER.debug` call in the code and my log level is set to debug.
```
2024-07-26 16:09:01.484 DEBUG (MainThread) [custom_components.hubspace.coordinator] Adding device XXXroom to light
2024-07-26 16:09:01.484 DEBUG (MainThread) [custom_components.hubspace.coordinator] Adding device Front Door to lock
2024-07-26 16:09:01.484 DEBUG (MainThread) [custom_components.hubspace.coordinator] Adding device Plug to switch
2024-07-26 16:09:01.484 DEBUG (MainThread) [custom_components.hubspace.coordinator] Finished fetching hubspace data in 0.380
```

**Comment by Expl0dingBanana** [comment]
@bluedragon456 Thanks for the data dump! Ill add this in and fix the issues I see pop up

@jdeath After trying the valve, I noticed the coordinator was not being called for valves either. I need to look deeper into the code and see if these only respect async_update vs coordinate updates. That would make sense that this is the root of the issue.

**Comment by Expl0dingBanana** [comment]
@jdeath please pull and test again. `CoordinatorEntity` has been added to locks, switches, and valves. I wonder if it needs to be added to Sensors too. Let me poke around with that some and find out

**Comment by Expl0dingBanana** [comment]
I found an issue where multiple spigots (and i assume switches) discover with the same friendlyname due to how reporting works from HS API. Going to look into this,

**Comment by jdeath** [comment]
> `CoordinatorEntity` has been added to locks, switches, and valves.

Yup. That worked. This is why I kept it so simple before!

All my devices now work. Once you are comfortable with getting a million support requests, I will merge and try to figure out how to make you an editor of the repo.

So this should auto learn the API of new models? I just got a new fan request, might be a good test if that just works..

**Comment by Expl0dingBanana** [comment]
Lets point the new fan request in this direction and see if everything works as expected. I also need to adjust the dump of a RGB light and see if it works accordingly. Once that works (and the water-timer), I think I am good with this being merged. I figure if it continues to work for several months with no requests, I can try to add it into the platform as a HA integration, rather than a HACS integration.

@bluedragon456 can you verify that the water-timer works as expected?

**Comment by bluedragon456** [comment]
It now shows the two valves. and has controls but fails when trying to use them. message I get is
image
so, looks like it's not calling to the valve just the main timer.

**Comment by bluedragon456** [comment]
Also noticed that the way it pulls in isn't quite right. The unit pulls in more like the fans you have the main unit and then it pulls in the child names for the light and fan. In the app they have it setup like that for the water time the main unit's name and then you can go into it and name each spigot.

**Comment by Expl0dingBanana** [comment]
@bluedragon456 hrmm I only see two devices in the dump so I assumed one was the main timer, and the others were for controlling the valve. I will need a full dump of the API results to figure out whats going on since they look identical. Would it be possible to provide the output from TestHubspace.py?

**Comment by bluedragon456** [comment]
I am trying but my skill with this stuff is not great. I can get the test to run but the info given back is too large to copy and paste out and I am not finding a way to output in to be able to send it. I tried using the terminal in HA but that doesn't allow me to scroll. I used github codespace and can scroll but the terminal doesn't hold enough data so I can see it all. So, I am stuck on how to output the data so I can get it over to you.

**Comment by Expl0dingBanana** [comment]
@bluedragon456 no worries! I added a new cli command that can dump this raw data to a file. You will need to re-download the file from the README as its changed.

`python anonomyize_data.py --username "<username>" --password "<password>" raw-data`

This will output a file, `raw-data.json` in the folder you run it. From there, you can run it through the anonymizer (sample_data/anonymize_data) with `python anonymize_data.py --infile raw-data.json --outfile raw-data-anon.json`. Unfortunately the other anonymizer shouldn't normally be needed so it is not included with HACS so I am not comfortable adding that call to the CLI tool.

**Comment by Expl0dingBanana** [comment]
@bluedragon456 I have updated the troubleshooting section and provided a way to do this through the Home Assistant UI (although it does require an additional add-on to download the file from the UI).

**Comment by jdeath** [comment]
neat. I think 99% of people use the Samba Share add-on, so that can get the files too.

**Comment by bluedragon456** [comment]
Here is the latest pull of data. Sorry for the delay and thank you for making the troubleshooter version. I wish I knew more but I am still new to that side of things. So, thank you for looking ahead and helping. 
[_dump_hs_devices.json](https://github.com/user-attachments/files/16405316/_dump_hs_devices.json)
I hope it gets what you need if you need, I can send a raw one as well.

**Comment by Expl0dingBanana** [comment]
I think I may need the full data dump. I see the one device for the water-timer but you said that there should be sub-devices for the spigots. I wonder if they have `children` populated so I toss them, or something else funky is going on. Please shoot me the full data dump, `_dump_hs_raw.json`. This is non-anonymized, (mostly) raw data from the HS API. I must not be accounting for something for this device type.

**Comment by Expl0dingBanana** [comment]
@jdeath do you have a pypi account? I can add maintainer rights to https://pypi.org/project/hubspace-async/ as thats the supporting HS API code for this project.

**Comment by bluedragon456** [comment]
Here is the raw file. 
[_dump_hs_raw.json](https://github.com/user-attachments/files/16420280/_dump_hs_raw.json)
The water time is under the name gardendrip and the spigots are spigot 1 and spigot 2.  There may also be the issue that the water timer is not a wifi device, it must be bridged to the plug that it comes with or another supported model. Which is under the name hubspacehubplug.

**Comment by Expl0dingBanana** [comment]
Thanks for that! When you used discovery before, what friendlyName did you use?

**Comment by Expl0dingBanana** [comment]
I just reviewed the error message. I think I am calling the right device, but something else is going on. let me review the entity and see whats going on.

**Comment by jdeath** [comment]
> @jdeath do you have a pypi account? I can add maintainer rights to https://pypi.org/project/hubspace-async/ as thats the supporting HS API code for this project.

I don't. I never could figure packages out, so stayed away. I'll send you rights to this repo as you'll have to handle a majority of the updates until I can figure it out.

**Comment by bluedragon456** [comment]
I always have had it set as gardendrip for the main timer. While working with it I noticed I forgot to rename them back to normal when I was trying to figure out the water timer and few months ago. The spigot name may have changed with that from 1 to spigot 1 and the same for spigot 2.

**Comment by Expl0dingBanana** [comment]
I think this is related to supported_features, which isnt covered by the docs but the code.
https://github.com/home-assistant/core/blob/dev/homeassistant/components/valve/__init__.py#L195

Let me review the core code and I will get a PR out shortly

**Comment by Expl0dingBanana** [comment]
@bluedragon456 can you re-pull and see if it works now? The error message stated supporting a service, not the API call failed. Upon reviewing the code, I think that was due to supported features not being set. I think all HubSpace valves support open / close so that got hard-coded.

**Comment by bluedragon456** [comment]
Sound good just incase I didn't mention it. The spigot 1 valve does report when it is turned on and off. But no controls and spigot 2 doesn't see when it been activated, no controls. And the battery sensor is working.

**Comment by bluedragon456** [comment]
Trying the fix now

**Comment by Expl0dingBanana** [comment]
I forgot the property in the last push. Can you give it one more refresh?

**Comment by bluedragon456** [comment]
Yeah just with the testing done on the last one it started working but spigot 2 doesn't report the change when turning on manually. I pull again and let you know the changes

**Comment by Expl0dingBanana** [comment]
Updates can take up to 30s (the poll time not to spam the HS API).

**Comment by bluedragon456** [comment]
It is working but I am seeing an issue with the spigot 2. When turned on it will turn off after a few seconds. The valve on the device stays running. They show an issue with the naming both list the same name they don't have different id. I have included a photo that shows this as well as the log. The log is me turning on spigot 2 and waiting for it to turn off. Spigot 1 is working and controlling as I would expect. 
Hubspace capture
Hubspace capture1

**Comment by Expl0dingBanana** [comment]
The last push should fix the naming issue as it will include the spigot as part of the name. It should be `gardendrip - spigot 1` and `gardendrip - spigot 2` now. The backend should have different IDs but the frontend displayed the incorrect names. I am not sure what would cause the state issue though.

Are there any warnings errors around the API call failing for the closure of the valve?

**Comment by Expl0dingBanana** [comment]
@bluedragon456 I think the issue was with how I was handling states as I was only comparing half of the values needed to ensure I was working on the correct state. Please let me know if you still have any issues after this latest push.

**Comment by bluedragon456** [comment]
That work. It's all working and report as expected. Thank you for work on this again.

**Comment by Expl0dingBanana** [comment]
Perfect! Glad its working now.

@jdeath I think this is good to be squashed merged. The only device class that exists that hasnt been tested has been `landscape-transformer`, but that follows the same logic as an switch / outlet. An outlet has been tested. `landscape-transformers` do not currently support stating watts / volts since I do not have a data dump for this device. I am unsure if its tied per-outlet or overall. My best guess would be overall but I dont want to implement it as such.

**Comment by jdeath** [comment]
Yes, it is overall. I just did a hack and pulled the data into the first outlet because I did not know how to make separate sensors. Ok, I'll do the PR. Do a release in a day or so, as that will invite an onslaught of issues.

**Pull request merged**
