### PR TITLE
Merge Discovery

### PR DESCRIPTION
**Pull request by Expl0dingBanana**
This is probably an API break as I do not have json dumps to ensure things are working. If model is not determined when reading from the API and had elements force set, those could be lost.

* Convert discovery to determine deviceIds to add during discovery
* Move all discovery code into a single pipeline
* Update lights to support on/off, brightness, and color temps (I dont believe RBG was configurable in the current setup)
* Create a new call to hubspace that can update multiple attributes in a single call
* ( #71  ) Fix Zandra Fans being unable to control lights
* Cleanup a bunch of unused code after the migration
* Fix an issue where auto-discovery would not discovery fans

This is currently running against my Zandra fan. The light works as expected but there are changed needed to the fan as the speed is off (0%) or on (20%) and I cannot adjust it from there. This issue existed prior to my changes.

image

### CODE REVIEW

**Comment by Expl0dingBanana** [comment]
@jdeath Have you been able to take a look at this?

**Comment by jdeath** [comment]
I haven't yet. I'll be away for a few more days. Did you do a read me update to go with breaking change?

**Comment by Expl0dingBanana** [comment]
This may or may not be a breaking change. I was not sure how to support RGB so that functionality doesnt work. I would need to take another look at the code to see if HubSpace has any RGB lights and review previous code on that too.

Do you have a sample of RGB lights to reference so I can write some tests to ensure they still work?

**Comment by Expl0dingBanana** [comment]
Closing since #86 is now open.

**Pull request closed without merging**
